# Generated by Django 4.2.1 on 2023-06-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0002_usuario_imagen_perfil_usuario_nombre_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/perfil/'),
        ),
    ]
